---
- name: Deploy Todo App (copy from Git)
  hosts: localhost
  become: yes               # Activar sudo
  become_user: root         # Ejecutar como root
  vars:
    app_dest: /var/www/todo-app
    git_repo: https://github.com/Equipo4DevSecOps/todo-app.git
    git_version: main       # Rama a usar

  tasks:
    - name: Ensure app directory exists
      file:
        path: "{{ app_dest }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Clone or update Git repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ app_dest }}"
        version: "{{ git_version }}"
        force: yes
        update: yes
        accept_hostkey: yes
      become: yes

    - name: Set permissions recursively
      file:
        path: "{{ app_dest }}"
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'
      become: yes
